name:                data-sketches-core
version:             0.1.0.0
github:              "iand675/datasketches-haskell"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "2021 Ian Duncan, Rob Bassi, Mercury Technologies"

default-extensions:
- BangPatterns
- FlexibleInstances
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TypeFamilies
- TypeOperators

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/datasketches-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq
- ghc-prim
- vector
- vector-algorithms
- primitive
- mwc-random

library:
  source-dirs: src

tests:
  data-sketches-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-sketches-core
